variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
    - build
    - test
    - docker

build:
    stage: build
    script:
        - ./gradlew assemble

test:
    stage: test
    script:
        - ./gradlew test

docker:
    stage: docker
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker run -d --name mysql-db -e MYSQL_ROOT_PASSWORD=root_password -e MYSQL_DATABASE=your_database_name -e MYSQL_USER=user -e MYSQL_PASSWORD=password -p 3306:3306 mysql:8.0
        - docker build -t fur-ever-friends-app .
        - sleep 20  # Wait for MySQL to be fully up and running
        - docker run -d --name fur-ever-friends-container-be -p 8080:8080 --link mysql-db:mysql fur-ever-friends-app
